version: '3.7'
services:
  db:
    image: postgres:14
    container_name: prex_db
    env_file: .env
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
  node:
    build: .
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - ${PORT}:3000
    depends_on:
      - db

volumes:
  db:
    external: false
